import React from 'react';
import './About.css'


const About = () => {
    return (
        
        <div className='container'>
            <h1>About This Application</h1>
            <p>This application is a simple product store built with React and React Router.</p>
            <p>It demonstrates how to implement routing and dynamic pages.</p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis beatae, reiciendis quos ab aliquam ipsa numquam architecto doloremque necessitatibus neque, praesentium alias voluptatem, tempore consequuntur unde tenetur nostrum sit amet.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad veniam excepturi maxime hic similique, quia assumenda? Dolores porro quo dicta dolorem sequi veritatis at harum ratione ipsum excepturi quas beatae, possimus, magni blanditiis alias. Cupiditate repellat aut impedit, similique minima autem, quaerat beatae unde harum odio ab nobis aspernatur, reiciendis ratione deserunt laudantium. Possimus nesciunt corporis magnam facilis id, porro vitae aut voluptatem voluptate dolorum nemo accusamus velit quam quis similique deleniti! Est, recusandae. Saepe optio minima beatae nulla architecto facilis quos iusto hic ab voluptates excepturi ullam atque, rem vero reiciendis autem, error dolores facere doloribus. Nisi, quaerat eum!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis beatae, reiciendis quos ab aliquam ipsa numquam architecto doloremque necessitatibus neque, praesentium alias voluptatem, tempore consequuntur unde tenetur nostrum sit amet.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad veniam excepturi maxime hic similique, quia assumenda? Dolores porro quo dicta dolorem sequi veritatis at harum ratione ipsum excepturi quas beatae, possimus, magni blanditiis alias. Cupiditate repellat aut impedit, similique minima autem, quaerat beatae unde harum odio ab nobis aspernatur, reiciendis ratione deserunt laudantium. Possimus nesciunt corporis magnam facilis id, porro vitae aut voluptatem voluptate dolorum nemo accusamus velit quam quis similique deleniti! Est, recusandae. Saepe optio minima beatae nulla architecto facilis quos iusto hic ab voluptates excepturi ullam atque, rem vero reiciendis autem, error dolores facere doloribus. Nisi, quaerat eum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo in facere repellendus laborum dolore quas mollitia officiis quod, neque tempora aliquam placeat nihil quis voluptatum totam explicabo eligendi. Minima autem ratione adipisci. Fugiat, provident omnis nihil necessitatibus optio ipsa deserunt assumenda corporis quaerat doloremque facere quos eos fugit. Optio magni porro totam, impedit illum eum numquam necessitatibus debitis vel assumenda maxime facere excepturi, veritatis reprehenderit architecto, ipsa cupiditate. Vero maxime officia aut animi! Neque maxime quasi cupiditate molestiae ipsum accusantium rerum deserunt sequi, facilis est distinctio vero numquam pariatur. Dolorum nulla aut magni esse expedita excepturi officiis blanditiis qui sequi.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis beatae, reiciendis quos ab aliquam ipsa numquam architecto doloremque necessitatibus neque, praesentium alias voluptatem, tempore consequuntur unde tenetur nostrum sit amet.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad veniam excepturi maxime hic similique, quia assumenda? Dolores porro quo dicta dolorem sequi veritatis at harum ratione ipsum excepturi quas beatae, possimus, magni blanditiis alias. Cupiditate repellat aut impedit, similique minima autem, quaerat beatae unde harum odio ab nobis aspernatur, reiciendis ratione deserunt laudantium. Possimus nesciunt corporis magnam facilis id, porro vitae aut voluptatem voluptate dolorum nemo accusamus velit quam quis similique deleniti! Est, recusandae. Saepe optio minima beatae nulla architecto facilis quos iusto hic ab voluptates excepturi ullam atque, rem vero reiciendis autem, error dolores facere doloribus. Nisi, quaerat eum!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis beatae, reiciendis quos ab aliquam ipsa numquam architecto doloremque necessitatibus neque, praesentium alias voluptatem, tempore consequuntur unde tenetur nostrum sit amet.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad veniam excepturi maxime hic similique, quia assumenda? Dolores porro quo dicta dolorem sequi veritatis at harum ratione ipsum excepturi quas beatae, possimus, magni blanditiis alias. Cupiditate repellat aut impedit, similique minima autem, quaerat beatae unde harum odio ab nobis aspernatur, reiciendis ratione deserunt laudantium. Possimus nesciunt corporis magnam facilis id, porro vitae aut voluptatem voluptate dolorum nemo accusamus velit quam quis similique deleniti! Est, recusandae. Saepe optio minima beatae nulla architecto facilis quos iusto hic ab voluptates excepturi ullam atque, rem vero reiciendis autem, error dolores facere doloribus. Nisi, quaerat eum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo in facere repellendus laborum dolore quas mollitia officiis quod, neque tempora aliquam placeat nihil quis voluptatum totam explicabo eligendi. Minima autem ratione adipisci. Fugiat, provident omnis nihil necessitatibus optio ipsa deserunt assumenda corporis quaerat doloremque facere quos eos fugit. Optio magni porro totam, impedit illum eum numquam necessitatibus debitis vel assumenda maxime facere excepturi, veritatis reprehenderit architecto, ipsa cupiditate. Vero maxime officia aut animi! Neque maxime quasi cupiditate molestiae ipsum accusantium rerum deserunt sequi, facilis est distinctio vero numquam pariatur. Dolorum nulla aut magni esse expedita excepturi officiis blanditiis qui sequi.
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis beatae, reiciendis quos ab aliquam ipsa numquam architecto doloremque necessitatibus neque, praesentium alias voluptatem, tempore consequuntur unde tenetur nostrum sit amet.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad veniam excepturi maxime hic similique, quia assumenda? Dolores porro quo dicta dolorem sequi veritatis at harum ratione ipsum excepturi quas beatae, possimus, magni blanditiis alias. Cupiditate repellat aut impedit, similique minima autem, quaerat beatae unde harum odio ab nobis aspernatur, reiciendis ratione deserunt laudantium. Possimus nesciunt corporis magnam facilis id, porro vitae aut voluptatem voluptate dolorum nemo accusamus velit quam quis similique deleniti! Est, recusandae. Saepe optio minima beatae nulla architecto facilis quos iusto hic ab voluptates excepturi ullam atque, rem vero reiciendis autem, error dolores facere doloribus. Nisi, quaerat eum!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis beatae, reiciendis quos ab aliquam ipsa numquam architecto doloremque necessitatibus neque, praesentium alias voluptatem, tempore consequuntur unde tenetur nostrum sit amet.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad veniam excepturi maxime hic similique, quia assumenda? Dolores porro quo dicta dolorem sequi veritatis at harum ratione ipsum excepturi quas beatae, possimus, magni blanditiis alias. Cupiditate repellat aut impedit, similique minima autem, quaerat beatae unde harum odio ab nobis aspernatur, reiciendis ratione deserunt laudantium. Possimus nesciunt corporis magnam facilis id, porro vitae aut voluptatem voluptate dolorum nemo accusamus velit quam quis similique deleniti! Est, recusandae. Saepe optio minima beatae nulla architecto facilis quos iusto hic ab voluptates excepturi ullam atque, rem vero reiciendis autem, error dolores facere doloribus. Nisi, quaerat eum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo in facere repellendus laborum dolore quas mollitia officiis quod, neque tempora aliquam placeat nihil quis voluptatum totam explicabo eligendi. Minima autem ratione adipisci. Fugiat, provident omnis nihil necessitatibus optio ipsa deserunt assumenda corporis quaerat doloremque facere quos eos fugit. Optio magni porro totam, impedit illum eum numquam necessitatibus debitis vel assumenda maxime facere excepturi, veritatis reprehenderit architecto, ipsa cupiditate. Vero maxime officia aut animi! Neque maxime quasi cupiditate molestiae ipsum accusantium rerum deserunt sequi, facilis est distinctio vero numquam pariatur. Dolorum nulla aut magni esse expedita excepturi officiis blanditiis qui sequi.
     
        </div>
    );
};

export default About;