import React from 'react'

export const Services = () => {
  return (
    <div>
        <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis deleniti a quo optio fuga quos officiis laborum quasi expedita itaque? Corrupti, quaerat dignissimos! Exercitationem aperiam nam tempore quo autem facilis quidem, fugit iure eius rem laborum, beatae officiis voluptate illum omnis quae placeat nobis suscipit incidunt nemo, repudiandae deserunt id culpa? Illo quia nulla veniam facilis doloribus fuga illum quod iste, tenetur dolorum! Iusto fugit inventore nulla maiores, repellat tempora voluptatum quaerat cum non similique unde sapiente, labore, blanditiis totam soluta id incidunt eveniet nobis. Omnis consequatur explicabo quaerat. Laborum a tempore omnis pariatur eaque et dolorem quaerat necessitatibus sed.</div>
   <br />
   <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis deleniti a quo optio fuga quos officiis laborum quasi expedita itaque? Corrupti, quaerat dignissimos! Exercitationem aperiam nam tempore quo autem facilis quidem, fugit iure eius rem laborum, beatae officiis voluptate illum omnis quae placeat nobis suscipit incidunt nemo, repudiandae deserunt id culpa? Illo quia nulla veniam facilis doloribus fuga illum quod iste, tenetur dolorum! Iusto fugit inventore nulla maiores, repellat tempora voluptatum quaerat cum non similique unde sapiente, labore, blanditiis totam soluta id incidunt eveniet nobis. Omnis consequatur explicabo quaerat. Laborum a tempore omnis pariatur eaque et dolorem quaerat necessitatibus sed.</div>
   <br />
   <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis deleniti a quo optio fuga quos officiis laborum quasi expedita itaque? Corrupti, quaerat dignissimos! Exercitationem aperiam nam tempore quo autem facilis quidem, fugit iure eius rem laborum, beatae officiis voluptate illum omnis quae placeat nobis suscipit incidunt nemo, repudiandae deserunt id culpa? Illo quia nulla veniam facilis doloribus fuga illum quod iste, tenetur dolorum! Iusto fugit inventore nulla maiores, repellat tempora voluptatum quaerat cum non similique unde sapiente, labore, blanditiis totam soluta id incidunt eveniet nobis. Omnis consequatur explicabo quaerat. Laborum a tempore omnis pariatur eaque et dolorem quaerat necessitatibus sed.</div>
   <br />
   <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis deleniti a quo optio fuga quos officiis laborum quasi expedita itaque? Corrupti, quaerat dignissimos! Exercitationem aperiam nam tempore quo autem facilis quidem, fugit iure eius rem laborum, beatae officiis voluptate illum omnis quae placeat nobis suscipit incidunt nemo, repudiandae deserunt id culpa? Illo quia nulla veniam facilis doloribus fuga illum quod iste, tenetur dolorum! Iusto fugit inventore nulla maiores, repellat tempora voluptatum quaerat cum non similique unde sapiente, labore, blanditiis totam soluta id incidunt eveniet nobis. Omnis consequatur explicabo quaerat. Laborum a tempore omnis pariatur eaque et dolorem quaerat necessitatibus sed.</div>
   <br />
   <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis deleniti a quo optio fuga quos officiis laborum quasi expedita itaque? Corrupti, quaerat dignissimos! Exercitationem aperiam nam tempore quo autem facilis quidem, fugit iure eius rem laborum, beatae officiis voluptate illum omnis quae placeat nobis suscipit incidunt nemo, repudiandae deserunt id culpa? Illo quia nulla veniam facilis doloribus fuga illum quod iste, tenetur dolorum! Iusto fugit inventore nulla maiores, repellat tempora voluptatum quaerat cum non similique unde sapiente, labore, blanditiis totam soluta id incidunt eveniet nobis. Omnis consequatur explicabo quaerat. Laborum a tempore omnis pariatur eaque et dolorem quaerat necessitatibus sed.</div>
   <br />
   <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis deleniti a quo optio fuga quos officiis laborum quasi expedita itaque? Corrupti, quaerat dignissimos! Exercitationem aperiam nam tempore quo autem facilis quidem, fugit iure eius rem laborum, beatae officiis voluptate illum omnis quae placeat nobis suscipit incidunt nemo, repudiandae deserunt id culpa? Illo quia nulla veniam facilis doloribus fuga illum quod iste, tenetur dolorum! Iusto fugit inventore nulla maiores, repellat tempora voluptatum quaerat cum non similique unde sapiente, labore, blanditiis totam soluta id incidunt eveniet nobis. Omnis consequatur explicabo quaerat. Laborum a tempore omnis pariatur eaque et dolorem quaerat necessitatibus sed.</div>
   <br />
   <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis deleniti a quo optio fuga quos officiis laborum quasi expedita itaque? Corrupti, quaerat dignissimos! Exercitationem aperiam nam tempore quo autem facilis quidem, fugit iure eius rem laborum, beatae officiis voluptate illum omnis quae placeat nobis suscipit incidunt nemo, repudiandae deserunt id culpa? Illo quia nulla veniam facilis doloribus fuga illum quod iste, tenetur dolorum! Iusto fugit inventore nulla maiores, repellat tempora voluptatum quaerat cum non similique unde sapiente, labore, blanditiis totam soluta id incidunt eveniet nobis. Omnis consequatur explicabo quaerat. Laborum a tempore omnis pariatur eaque et dolorem quaerat necessitatibus sed.</div>
   <br />
    </div>
  )
}
